### ISSUE TITLE
Script stuck after generating

### ISSUE THREAD

**Issue by NZXTsh** [AceBeaker2/Vyper-Spammer#1]
The program is getting stuck after it generated the info

**Comment by acebeakerxyz** [comment]
Hi, the script is currently broken, I'll push a commit to fix it today

**Comment by acebeakerxyz** [comment]
Hi! please pull the latest commit and test again

**Comment by NZXTsh** [comment]
i did its still the same problem 

screen: https://ibb.co/kxvD5D1

> Hi! please pull the latest commit and test again

**Comment by acebeakerxyz** [comment]
Please check that the mail server is working by sending an email to [something]@[yourdomain].com . If that works, please provide the output of python3 abuse.py -v

**Comment by NZXTsh** [comment]
<bound method ClientResponse.text of <ClientResponse(https://vyper.io/entries/view/20397510qZbD?new=1&display_type=Landing+Page) [200 OK]>
<CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'Caddy', 'Set-Cookie': 'pageview=774ed94039f32ce135926b15bf50b852d614339d9985fb2f41498280f15c32eca%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22pageview%22%3Bi%3A1%3Bi%3A444977%3B%7D; path=/; HttpOnly', 'Vary': 'Accept-Encoding', 'X-Debug': 'test', 'Date': 'Fri, 25 Aug 2023 18:08:00 GMT', 'Transfer-Encoding': 'chunked')>
> thats the output

**Comment by acebeakerxyz** [comment]
And is the mail server working?

**Comment by NZXTsh** [comment]
Yea i tested it

**Comment by acebeakerxyz** [comment]
It seems like vyper is receiving your api call and not sending you a verification email.

**Comment by NZXTsh** [comment]
Im using hostinger

**Comment by NZXTsh** [comment]
Anything else i could try i really need the bot would be useful

**Comment by acebeakerxyz** [comment]
go into chrome dev tools and keep the network tab open while referring yourself with the link, then when you see the request that starts with create, copy that as curl(bash), and send it here. I'll send you a modified version of vyperapi.py that should work better

**Comment by NZXTsh** [comment]
curl 'https://vyper.io/entries/create?contest_id=444977&referrer_id=20141761&display_type=Landing%20Page' \
  -H 'authority: vyper.io' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'cache-control: max-age=0' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryIl0fsi7syW9Ayo1Y' \
  -H 'origin: https://vy.lc' \
  -H 'referer: https://vy.lc/' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  --data-raw $'------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="_csrf"\r\n\r\nNVF1bFYtWVdmPSQ6ZxwwNl0zMlQTbxQ0czM2GhkaEBpdOhMEOhs/FA==\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="Entries[contest_id]"\r\n\r\n444977\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="Entries[referrer_id]"\r\n\r\n20141761\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="Entries[registration_ip]"\r\n\r\n54.151.31.245\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="Entries[gc]"\r\n\r\n1e213483\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="Entries[full_name]"\r\n\r\njhg\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="Entries[email]"\r\n\r\nfjh@gmail.com\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="Entries[custom_entry_field1]"\r\n\r\n4345\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="terms_text"\r\n\r\non\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y\r\nContent-Disposition: form-data; name="g-recaptcha-response"\r\n\r\n\r\n------WebKitFormBoundaryIl0fsi7syW9Ayo1Y--\r\n' \
  --compressed

**Comment by NZXTsh** [comment]
Is this the right one

**Comment by acebeakerxyz** [comment]
Im sorry but I can't help you anymore. Im closing down this repository due to fear of a DMCA takedown

**Comment by AceBeaker2** [comment]
You should not reach out on discord and don't contact me @ace_beaker on discord where I won't patch the problem and I won't help guide you through setting it up
